// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{
    MERKLE_ELF, MERKLE_ID,
};
use risc0_zkvm::{default_prover, ExecutorEnv, InnerReceipt};
use risc0_zkvm::sha::{Digest, Impl, Sha256};
use merkle_proof::MerkleProof;

fn get_merkle_proof() -> MerkleProof<Digest> {
    //             root
    //    h(0,0)            h(leaf, 0)
    // 0          0     leaf          0

    let leaf_value = Digest::from([1; 8]); // index 6
    let parent_value = *Impl::hash_bytes(&[leaf_value.as_bytes(), Digest::ZERO.as_bytes()].concat()); // index 3
    let uncle_value = *Impl::hash_bytes(&[Digest::ZERO.as_bytes(), Digest::ZERO.as_bytes()].concat()); // index 2
    let root_value = *Impl::hash_bytes(&[uncle_value.as_bytes(), parent_value.as_bytes()].concat()); // index 1

    MerkleProof {
        root: root_value,
        nodes: vec![leaf_value, Digest::ZERO, uncle_value],
        leaf_index: 6,
    }
}

fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    let env = ExecutorEnv::builder()
        .write(&get_merkle_proof())
        .unwrap()
        .build()
        .unwrap();

    let prover = default_prover();

    let receipt = prover
        .prove(env, MERKLE_ELF)
        .unwrap();

    let merkle_proof_validity: bool = receipt.journal.decode().unwrap();
    assert!(merkle_proof_validity, "Merkle proof is invalid");

    receipt
        .verify(MERKLE_ID)
        .unwrap();

    let InnerReceipt::Composite(composite) = receipt.inner else {
        panic!("Expected composite receipt");
    };
    println!("We got a composite receipt with {} segments. Total size of STARKs is {} kB",
             composite.segments.len(),
             composite.segments.iter().map(|s| s.seal.len()).sum::<usize>() / 256 // seal is over u32
    );
}
