// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{
    MERKLE_ELF, MERKLE_ID,
};
use risc0_zkvm::{default_prover, ExecutorEnv, InnerReceipt};
use risc0_zkvm::sha::{Digest, Impl, Sha256};
use merkle_proof::MerkleProof;

fn hash(left: Digest, right: Digest) -> Digest {
    *Impl::hash_bytes(&[left.as_bytes(), right.as_bytes()].concat())
}

#[allow(dead_code)]
fn get_short_merkle_proof() -> MerkleProof<Digest> {
    //             root
    //    h(0,0)            h(leaf, 0)
    // 0          0     leaf          0

    let leaf_value = Digest::from([1; 8]);              // index 6
    let parent_value = hash(leaf_value, Digest::ZERO);  // index 3
    let uncle_value = hash(Digest::ZERO, Digest::ZERO); // index 2
    let root_value = hash(uncle_value, parent_value);   // index 1

    MerkleProof {
        root: root_value,
        nodes: vec![leaf_value, Digest::ZERO, uncle_value],
        leaf_index: 6,
    }
}

fn get_long_merkle_proof() -> MerkleProof<Digest> {
    let leaf_value = Digest::from([1; 8]);
    let leaf_index = (1u64 << 34) + (1u64 << 33);

    let mut index = leaf_index;
    let nodes = [vec![leaf_value], Vec::from([Digest::ZERO; 34])].concat();

    let mut current_hash = leaf_value;
    while index > 1 {
        if index % 2 == 0 {
            current_hash = hash(current_hash, Digest::ZERO);
        } else {
            current_hash = hash(Digest::ZERO, current_hash);
        }
        index /= 2;
    }

    MerkleProof {
        root: current_hash,
        nodes,
        leaf_index,
    }
}

fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    let env = ExecutorEnv::builder()
        .write(&get_long_merkle_proof())
        .unwrap()
        .build()
        .unwrap();

    let prover = default_prover();

    let receipt = prover
        .prove(env, MERKLE_ELF)
        .unwrap();

    let merkle_proof_validity: bool = receipt.journal.decode().unwrap();
    assert!(merkle_proof_validity, "Merkle proof is invalid");

    receipt
        .verify(MERKLE_ID)
        .unwrap();

    let InnerReceipt::Composite(composite) = receipt.inner else {
        panic!("Expected composite receipt");
    };
    println!("We got a composite receipt with {} segments. Total size of STARKs is {} kB",
             composite.segments.len(),
             composite.segments.iter().map(|s| s.seal.len()).sum::<usize>() / 256 // seal is over u32
    );
}
